version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    environment:
      DJANGO_DB_HOST: mysql
      DJANGO_DB_ENGINE: mysql
      DJANGO_DB_NAME: technomart
      DJANGO_DB_USER: tm_user
      DJANGO_DB_PASSWORD: tm_password
      DJANGO_DB_PORT: "3306"
      DJANGO_DB_CONN_MAX_AGE: "60"
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    command: ["mysqld", "--mysql-native-password=ON", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: technomart
      MYSQL_USER: tm_user
      MYSQL_PASSWORD: tm_password
      MYSQL_ROOT_PASSWORD: root_password_change_me
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /workspace
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    env_file:
      - ./.env
    environment:
      VITE_DEV_PROXY_TARGET: http://api:8000
      VITE_API_BASE_URL: /api
      VITE_WS_URL: ws://localhost:8000/ws/events
    volumes:
      - .:/workspace
      - frontend-node-modules:/workspace/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  mysql-data:
  redis-data:
  frontend-node-modules:
